# Generated by Django 5.1.2 on 2025-04-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategiesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategies List',
                'ordering': ['user', 'title'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
