# Generated by Django 5.1.2 on 2025-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
