# Generated by Django 5.1.2 on 2025-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
