# Generated by Django 5.1.2 on 2025-04-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0004_profile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
    ]
