# Generated by Django 5.1.2 on 2025-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0006_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategieslist',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
