# Generated by Django 5.1.2 on 2025-04-22 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0007_strategieslist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategieslist',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 22)),
            preserve_default=False,
        ),
    ]
