# Generated by Django 5.1.2 on 2024-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_portfolio_delete_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='performance_percentage',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='exit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
