from django.db import models


class Stock(models.Model):
    ticker = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    ipo_year = models.IntegerField(null=True)
    sector = models.CharField(max_length=255)
    industry = models.CharField(max_length=255)
    market_cap = models.BigIntegerField(null=True)

    def __str__(self):
        return self.ticker


class FinancialReport(models.Model):
    """
    The column names are the same as the financials from yfinance but without spaces
    """
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateField(null=True)

    # Column names from yfinance->quarterly financials
    TaxEffectOfUnusualItems = models.BigIntegerField(null=True)
    TaxRateForCalcs = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    NormalizedEBITDA = models.BigIntegerField(null=True)
    NetIncomeFromContinuingOperationNetMinorityInterest = models.BigIntegerField(null=True)
    ReconciledDepreciation = models.BigIntegerField(null=True)
    ReconciledCostOfRevenue = models.BigIntegerField(null=True)
    EBITDA = models.BigIntegerField(null=True)
    EBIT = models.BigIntegerField(null=True)
    NetInterestIncome = models.BigIntegerField(null=True)
    InterestExpense = models.BigIntegerField(null=True)
    InterestIncome = models.BigIntegerField(null=True)
    NormalizedIncome = models.BigIntegerField(null=True)
    NetIncomeFromContinuingAndDiscontinuedOperation = models.BigIntegerField(null=True)
    TotalExpenses = models.BigIntegerField(null=True)
    TotalOperatingIncomeAsReported = models.BigIntegerField(null=True)
    DilutedAverageShares = models.BigIntegerField(null=True)
    BasicAverageShares = models.BigIntegerField(null=True)
    DilutedEPS = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    BasicEPS = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    DilutedNIAvailtoComStockholders = models.BigIntegerField(null=True)
    NetIncomeCommonStockholders = models.BigIntegerField(null=True)
    NetIncome = models.BigIntegerField(null=True)
    NetIncomeIncludingNoncontrollingInterests = models.BigIntegerField(null=True)
    NetIncomeContinuousOperations = models.BigIntegerField(null=True)
    TaxProvision = models.BigIntegerField(null=True)
    PretaxIncome = models.BigIntegerField(null=True)
    OtherIncomeExpense = models.BigIntegerField(null=True)
    OtherNonOperatingIncomeExpenses = models.BigIntegerField(null=True)
    NetNonOperatingInterestIncomeExpense = models.BigIntegerField(null=True)
    InterestExpenseNonOperating = models.BigIntegerField(null=True)
    InterestIncomeNonOperating = models.BigIntegerField(null=True)
    OperatingIncome = models.BigIntegerField(null=True)
    OperatingExpense = models.BigIntegerField(null=True)
    ResearchAndDevelopment = models.BigIntegerField(null=True)
    SellingGeneralAndAdministration = models.BigIntegerField(null=True)
    GrossProfit = models.BigIntegerField(null=True)
    CostOfRevenue = models.BigIntegerField(null=True)
    TotalRevenue = models.BigIntegerField(null=True)
    OperatingRevenue = models.BigIntegerField(null=True)


class BalanceSheet(models.Model):
    """
    The column names are the same as the balance sheet from yfinance but without spaces
    """
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateField(null=True)

    # Column names from yfinance->quarterly balance sheet
    TreasurySharesNumber = models.BigIntegerField(null=True)
    OrdinarySharesNumber = models.BigIntegerField(null=True)
    ShareIssued = models.BigIntegerField(null=True)
    NetDebt = models.BigIntegerField(null=True)
    TotalDebt = models.BigIntegerField(null=True)
    TangibleBookValue = models.BigIntegerField(null=True)
    InvestedCapital = models.BigIntegerField(null=True)
    WorkingCapital = models.BigIntegerField(null=True)
    NetTangibleAssets = models.BigIntegerField(null=True)
    CapitalLeaseObligations = models.BigIntegerField(null=True)
    CommonStockEquity = models.BigIntegerField(null=True)
    TotalCapitalization = models.BigIntegerField(null=True)
    TotalEquityGrossMinorityInterest = models.BigIntegerField(null=True)
    StockholdersEquity = models.BigIntegerField(null=True)
    GainsLossesNotAffectingRetainedEarnings = models.BigIntegerField(null=True)
    OtherEquityAdjustments = models.BigIntegerField(null=True)
    RetainedEarnings = models.BigIntegerField(null=True)
    CapitalStock = models.BigIntegerField(null=True)
    CommonStock = models.BigIntegerField(null=True)
    TotalLiabilitiesNetMinorityInterest = models.BigIntegerField(null=True)
    TotalNonCurrentLiabilitiesNetMinorityInterest = models.BigIntegerField(null=True)
    OtherNonCurrentLiabilities = models.BigIntegerField(null=True)
    TradeandOtherPayablesNonCurrent = models.BigIntegerField(null=True)
    LongTermDebtAndCapitalLeaseObligation = models.BigIntegerField(null=True)
    LongTermCapitalLeaseObligation = models.BigIntegerField(null=True)
    LongTermDebt = models.BigIntegerField(null=True)
    CurrentLiabilities = models.BigIntegerField(null=True)
    OtherCurrentLiabilities = models.BigIntegerField(null=True)
    CurrentDeferredLiabilities = models.BigIntegerField(null=True)
    CurrentDeferredRevenue = models.BigIntegerField(null=True)
    CurrentDebtAndCapitalLeaseObligation = models.BigIntegerField(null=True)
    CurrentCapitalLeaseObligation = models.BigIntegerField(null=True)
    CurrentDebt = models.BigIntegerField(null=True)
    OtherCurrentBorrowings = models.BigIntegerField(null=True)
    CommercialPaper = models.BigIntegerField(null=True)
    PayablesAndAccruedExpenses = models.BigIntegerField(null=True)
    Payables = models.BigIntegerField(null=True)
    TotalTaxPayable = models.BigIntegerField(null=True)
    IncomeTaxPayable = models.BigIntegerField(null=True)
    AccountsPayable = models.BigIntegerField(null=True)
    TotalAssets = models.BigIntegerField(null=True)
    TotalNonCurrentAssets = models.BigIntegerField(null=True)
    OtherNonCurrentAssets = models.BigIntegerField(null=True)
    NonCurrentDeferredAssets = models.BigIntegerField(null=True)
    NonCurrentDeferredTaxesAssets = models.BigIntegerField(null=True)
    InvestmentsAndAdvances = models.BigIntegerField(null=True)
    InvestmentinFinancialAssets = models.BigIntegerField(null=True)
    AvailableForSaleSecurities = models.BigIntegerField(null=True)
    NetPPE = models.BigIntegerField(null=True)
    AccumulatedDepreciation = models.BigIntegerField(null=True)
    GrossPPE = models.BigIntegerField(null=True)
    Leases = models.BigIntegerField(null=True)
    OtherProperties = models.BigIntegerField(null=True)
    MachineryFurnitureEquipment = models.BigIntegerField(null=True)
    LandAndImprovements = models.BigIntegerField(null=True)
    Properties = models.BigIntegerField(null=True)
    CurrentAssets = models.BigIntegerField(null=True)
    OtherCurrentAssets = models.BigIntegerField(null=True)
    Inventory = models.BigIntegerField(null=True)
    FinishedGoods = models.BigIntegerField(null=True)
    RawMaterials = models.BigIntegerField(null=True)
    Receivables = models.BigIntegerField(null=True)
    OtherReceivables = models.BigIntegerField(null=True)
    AccountsReceivable = models.BigIntegerField(null=True)
    CashCashEquivalentsAndShortTermInvestments = models.BigIntegerField(null=True)
    OtherShortTermInvestments = models.BigIntegerField(null=True)
    CashAndCashEquivalents = models.BigIntegerField(null=True)
    CashEquivalents = models.BigIntegerField(null=True)
    CashFinancial = models.BigIntegerField(null=True)


class CashFlow(models.Model):
    """
    The column names are the same as the cash flow from yfinance but without spaces
    """
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateField(null=True)

    # Column names from yfinance->quarterly cash flow
    FreeCashFlow0 = models.BigIntegerField(null=True)
    RepurchaseOfCapitalStock = models.BigIntegerField(null=True)
    RepaymentOfDebt = models.BigIntegerField(null=True)
    IssuanceOfDebt = models.BigIntegerField(null=True)
    CapitalExpenditure = models.BigIntegerField(null=True)
    InterestPaidSupplementalData = models.BigIntegerField(null=True)
    IncomeTaxPaidSupplementalData = models.BigIntegerField(null=True)
    EndCashPosition = models.BigIntegerField(null=True)
    BeginningCashPosition = models.BigIntegerField(null=True)
    ChangesInCash = models.BigIntegerField(null=True)
    FinancingCashFlow = models.BigIntegerField(null=True)
    CashFlowFromContinuingFinancingActivities = models.BigIntegerField(null=True)
    NetOtherFinancingCharges = models.BigIntegerField(null=True)
    CashDividendsPaid = models.BigIntegerField(null=True)
    CommonStockDividendPaid = models.BigIntegerField(null=True)
    NetCommonStockIssuance = models.BigIntegerField(null=True)
    CommonStockPayments = models.BigIntegerField(null=True)
    NetIssuancePaymentsOfDebt = models.BigIntegerField(null=True)
    NetShortTermDebtIssuance = models.BigIntegerField(null=True)
    ShortTermDebtPayments = models.BigIntegerField(null=True)
    NetLongTermDebtIssuance = models.BigIntegerField(null=True)
    LongTermDebtPayments = models.BigIntegerField(null=True)
    LongTermDebtIssuance = models.BigIntegerField(null=True)
    InvestingCashFlow = models.BigIntegerField(null=True)
    CashFlowFromContinuingInvestingActivities = models.BigIntegerField(null=True)
    NetOtherInvestingChanges = models.BigIntegerField(null=True)
    NetInvestmentPurchaseAndSale = models.BigIntegerField(null=True)
    SaleOfInvestment = models.BigIntegerField(null=True)
    PurchaseOfInvestment = models.BigIntegerField(null=True)
    NetPPEPurchaseAndSale = models.BigIntegerField(null=True)
    PurchaseOfPPE = models.BigIntegerField(null=True)
    OperatingCashFlow = models.BigIntegerField(null=True)
    CashFlowFromContinuingOperatingActivities = models.BigIntegerField(null=True)
    ChangeInWorkingCapital = models.BigIntegerField(null=True)
    ChangeInOtherCurrentLiabilities = models.BigIntegerField(null=True)
    ChangeInOtherCurrentAssets = models.BigIntegerField(null=True)
    ChangeInPayablesAndAccruedExpense = models.BigIntegerField(null=True)
    ChangeInPayable = models.BigIntegerField(null=True)
    ChangeInAccountPayable = models.BigIntegerField(null=True)
    ChangeInInventory = models.BigIntegerField(null=True)
    ChangeInReceivables = models.BigIntegerField(null=True)
    ChangesInAccountReceivables = models.BigIntegerField(null=True)
    OtherNonCashItems = models.BigIntegerField(null=True)
    StockBasedCompensation = models.BigIntegerField(null=True)
    DepreciationAmortizationDepletion = models.BigIntegerField(null=True)
    DepreciationAndAmortization = models.BigIntegerField(null=True)
    NetIncomeFromContinuingOperations = models.BigIntegerField(null=True)


class CandleStick(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateTimeField()
    open = models.DecimalField(max_digits=10, decimal_places=2)
    high = models.DecimalField(max_digits=10, decimal_places=2)
    low = models.DecimalField(max_digits=10, decimal_places=2)
    close = models.DecimalField(max_digits=10, decimal_places=2)
    adj_close = models.DecimalField(max_digits=10, decimal_places=2)
    volume = models.IntegerField()
