# Generated by Django 5.1.2 on 2025-05-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('ipo_year', models.IntegerField(null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
            ],
            options={
                'ordering': ['ticker', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDate', models.DateField(null=True)),
                ('StartDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('FiscalPeriod', models.CharField(blank=True, max_length=5, null=True)),
                ('ConsolidatedNetIncome', models.BigIntegerField(null=True)),
                ('DepreciationAndAmortization', models.BigIntegerField(null=True)),
                ('InvestmentGainsAndLossesNet', models.BigIntegerField(null=True)),
                ('DeferredIncomeTaxes', models.BigIntegerField(null=True)),
                ('OtherOperatingActivities', models.BigIntegerField(null=True)),
                ('ChangesInReceivablesNet', models.BigIntegerField(null=True)),
                ('ChangesInInventories', models.BigIntegerField(null=True)),
                ('ChangesInAccountsPayable', models.BigIntegerField(null=True)),
                ('ChangesInAccruedLiabilities', models.BigIntegerField(null=True)),
                ('ChangesInAccruedIncomeTaxes', models.BigIntegerField(null=True)),
                ('OperatingCashFlow', models.BigIntegerField(null=True)),
                ('PaymentsForPropertyAndEquipment', models.BigIntegerField(null=True)),
                ('ProceedsFromDisposalOfPropertyAndEquipment', models.BigIntegerField(null=True)),
                ('ProceedsFromDivestitureOfBusinesses', models.BigIntegerField(null=True)),
                ('ProceedsFromDisposalOfCertainStrategicInvestments', models.BigIntegerField(null=True)),
                ('OtherInvestingActivities', models.BigIntegerField(null=True)),
                ('InvestingCashFlow', models.BigIntegerField(null=True)),
                ('NetChangeInShortTermBorrowings', models.BigIntegerField(null=True)),
                ('ProceedsFromIssuanceOfLongTermDebt', models.BigIntegerField(null=True)),
                ('RepaymentsOfLongTermDebt', models.BigIntegerField(null=True)),
                ('DividendsPaid', models.BigIntegerField(null=True)),
                ('PurchaseOfCompanyStock', models.BigIntegerField(null=True)),
                ('DividendsPaidToNoncontrollingInterest', models.BigIntegerField(null=True)),
                ('SaleOfSubsidiaryStock', models.BigIntegerField(null=True)),
                ('PurchaseOfNoncontrollingInterest', models.BigIntegerField(null=True)),
                ('OtherFinancingActivities', models.BigIntegerField(null=True)),
                ('FinancingCashFlow', models.BigIntegerField(null=True)),
                ('EffectOfExchangeRatesOnCcashCashEquivalentsAndRestrictedCash', models.BigIntegerField(null=True)),
                ('NetIncreaseInCashCashEquivalentsAndRestrictedCash', models.BigIntegerField(null=True)),
                ('EndCashPosition', models.BigIntegerField(null=True)),
                ('PropertyAndEquipmentNet', models.BigIntegerField(null=True)),
                ('FreeCashFlow', models.BigIntegerField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-FileDate'],
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-FileDate'],
                'unique_together': {('stock', 'FileDate')},
            },
        ),
        migrations.CreateModel(
            name='CandleStick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('turnover', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-FileDate'],
                'unique_together': {('stock', 'FileDate')},
            },
        ),
    ]
