# Generated by Django 5.1.2 on 2025-01-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
    ]
