# Generated by Django 5.1.2 on 2025-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='Accounts Payable',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Accounts Payable, Current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Accounts Receivable',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Cash and Cash Equivalents',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Common Stock, Shares, Outstanding',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Current Assets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Debt to Equity',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Deferred Revenue, Current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Equity to Assets',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Increase (Decrease) in Accounts Payable',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Increase (Decrease) in Accounts Receivable',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Increase (Decrease) in Cash and Cash Equivalents',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Increase (Decrease) in Inventories',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Inventories, Finished Goods',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Inventory, Net',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Inventory, Raw Materials and Purchased Parts',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Liabilities',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Liabilities, Current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Liabilities, Noncurrent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Long-Lived Assets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Long-term Debt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Marketable Securities, Current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Marketable Securities, Noncurrent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Marketable Securities, Realized Gain (Loss)',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Retained Earnings',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Short-term Debt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name="Stockholders' Equity",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Taxes Payable, Current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Total Assets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Total Inventories',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Total Receivables',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Cost of Goods Sold',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Depreciation, Depletion and Amortization',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='EBITDA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='EBITDA Margin',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Earnings Per Share, Basic',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Earnings Per Share, Diluted',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Gross Margin',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Gross Profit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Interest Expense',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Investment Income, Interest and Dividend',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Net Income (Loss)',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Net Interest Income',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Net Margin',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Operating Income (Loss), EBIT',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Operating Margin',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Research and Development Expense',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Revenues',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Selling, General and Administrative Expense',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Total Operating Expenses',
            field=models.BigIntegerField(null=True),
        ),
    ]
