# Generated by Django 5.1.2 on 2025-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0002_balancesheet_accounts_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='Capital Expendtiures',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Cash Flow from Financing',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Cash Flow from Investing',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Cash Flow from Operations',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Depreciation, Depletion and Amortization',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Ending Cash Position',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Free Cash Flow',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Net Income (Loss) from Continuing Operations',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Purchase of Business',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Purchase of Investment',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Repurchase of Stock',
            field=models.BigIntegerField(null=True),
        ),
    ]
