# Generated by Django 5.1.2 on 2025-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0003_remove_incomestatement_basicearningpershareeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='BasicEarningPerShareEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='BasicWeightedAverageShares',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='ConsolidatedNetIncome',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='ConsolidatedNetIncomeAttributableToNoncontrollingInterest',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='ConsolidatedNetIncomeAttributableToThisCompany',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='CostOfSales',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='Debt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='DilutedEarningPerShareEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='DilutedWeightedAverageShares',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='DividendsPerShareDPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='FinanceLease',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='IncomeBeforeIncomeTaxes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='InterestIncome',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='InterestNet',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='NetSales',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='OperatingIncome',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='OperatingSellingGeneralAndAdministrativeExpenses',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='OtherIncome',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='OtherIncomeExpense',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='ProvisionForIncomeTaxes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='TotalRevenue',
            field=models.BigIntegerField(null=True),
        ),
    ]
