# Generated by Django 5.1.2 on 2025-01-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0004_incomestatement_basicearningpershareeps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='ShareIssued',
        ),
    ]
