# Generated by Django 5.1.2 on 2025-05-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0004_alter_cashflow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['stock__id', '-FileDate']},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('stock', 'FileDate', 'EndDate')},
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='FiscalPeriod',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='StartDate',
        ),
    ]
