# Generated by Django 5.1.2 on 2025-05-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0005_alter_cashflow_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('stock', 'FileDate')},
        ),
        migrations.CreateModel(
            name='PerShareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('Dividends per Share', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-FileDate'],
                'unique_together': {('stock', 'FileDate')},
            },
        ),
    ]
