# Generated by Django 5.1.2 on 2025-01-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0005_remove_balancesheet_shareissued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='end_date',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='start_date',
            new_name='StartDate',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='end_date',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='start_date',
            new_name='StartDate',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='end_date',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='start_date',
            new_name='StartDate',
        ),
    ]
