# Generated by Django 5.1.2 on 2025-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0006_alter_cashflow_unique_together_persharedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='persharedata',
            name='Cash per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='persharedata',
            name='EBIT per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='persharedata',
            name='EBITDA per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='persharedata',
            name='Free Cash Flow per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='persharedata',
            name='Operating Cash Flow per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='persharedata',
            name='Revenue per Shares',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
