# Generated by Django 5.1.2 on 2025-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0006_rename_end_date_balancesheet_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='FileDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='FileDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='FileDate',
            field=models.DateField(null=True),
        ),
    ]
