# Generated by Django 5.1.2 on 2025-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0007_balancesheet_filedate_cashflow_filedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
