# Generated by Django 5.1.2 on 2025-05-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0007_persharedata_cash_per_shares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='Liabilities',
            new_name='Total Liabilities',
        ),
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('Dividends per Share', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Revenue per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('EBIT per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('EBITDA per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Free Cash Flow per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Operating Cash Flow per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Cash per Shares', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Price to Earnings Ratio, PE Ratio', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('Price to Book Ratio, PB Ratio', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_database.stock')),
            ],
            options={
                'ordering': ['stock__id', '-FileDate'],
                'unique_together': {('stock', 'FileDate')},
            },
        ),
        migrations.DeleteModel(
            name='PerShareData',
        ),
    ]
