# Generated by Django 5.1.2 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0008_balancesheet_fiscalperiod_cashflow_fiscalperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='FiscalPeriod',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
