# Generated by Django 5.1.2 on 2025-01-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0009_alter_balancesheet_fiscalperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
    ]
