# Generated by Django 5.1.2 on 2025-02-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0010_stock_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlestick',
            name='adj_close',
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
