# Generated by Django 5.1.2 on 2025-03-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0012_alter_candlestick_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='CashAndCashEquivalents',
        ),
    ]
