# Generated by Django 5.1.2 on 2025-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0014_remove_balancesheet_shorttermborrowings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='CapitalExpenditure',
        ),
    ]
