# Generated by Django 5.1.2 on 2025-03-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0015_remove_cashflow_capitalexpenditure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='ProceedsFfromDisposalOfCertainOperations',
            new_name='ProceedsFromDivestitureOfBusinesses',
        ),
    ]
