# Generated by Django 5.1.2 on 2025-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0016_rename_proceedsffromdisposalofcertainoperations_cashflow_proceedsfromdivestitureofbusinesses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'ordering': ['stock__id', '-FileDate']},
        ),
        migrations.AlterModelOptions(
            name='candlestick',
            options={'ordering': ['stock__id', '-date']},
        ),
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['stock__id', '-FileDate']},
        ),
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['stock__id', '-FileDate']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticker', 'name']},
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='date',
            field=models.DateField(),
        ),
    ]
