# Generated by Django 5.1.2 on 2025-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0017_alter_balancesheet_options_alter_candlestick_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestick',
            name='turnover',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
