# Generated by Django 5.1.2 on 2025-04-08 21:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=6)),
                ('position_side_per_sector', models.IntegerField()),
                ('min_stock_price', models.IntegerField()),
                ('sort_ascending', models.BooleanField()),
                ('sector', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
