# Generated by Django 5.1.2 on 2025-04-17 14:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_area', '0002_strategieslist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongShortEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('market_cap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=6)),
                ('position_side_per_sector', models.IntegerField()),
                ('min_stock_price', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=500)),
                ('sort_ascending', models.BooleanField()),
                ('strategies_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longshort_equity', to='client_area.strategieslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longshort_equity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LongShort Equity',
                'verbose_name_plural': 'LongShort Equities',
                'ordering': ['name', '-created_at'],
                'unique_together': {('user', 'strategies_list', 'market_cap', 'position_side_per_sector', 'min_stock_price', 'sector', 'formula', 'sort_ascending')},
            },
        ),
    ]
