# Generated by Django 5.1.2 on 2025-04-22 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longshortequity',
            options={'ordering': ['name', '-created_on'], 'verbose_name': 'LongShort Equity', 'verbose_name_plural': 'LongShort Equities'},
        ),
        migrations.AddField(
            model_name='longshortequity',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 22)),
            preserve_default=False,
        ),
    ]
