# Generated by Django 5.1.2 on 2024-11-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0002_financialreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialreport',
            old_name='stock',
            new_name='symbol',
        ),
    ]
