# Generated by Django 5.1.2 on 2025-04-22 12:51

from django.db import migrations
from datetime import datetime
from ..models import LongShortEquity


def datetime_to_date(apps, schema_editor):
    LongShortEquity = apps.get_model('long_short_strategy', 'LongShortEquity')
    for strategy in LongShortEquity.objects.all():
        strategy.created_on = strategy.created_at.date()
        strategy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0002_alter_longshortequity_options_and_more'),
    ]

    operations = [
        migrations.RunPython(datetime_to_date)
    ]
