# Generated by Django 5.1.2 on 2024-11-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0003_rename_stock_financialreport_symbol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReport',
            new_name='FinancialReportQ22023',
        ),
    ]
