# Generated by Django 5.1.2 on 2025-04-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0003_move_datetime_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longshortequity',
            name='created_at',
        ),
    ]
