# Generated by Django 5.1.2 on 2025-05-09 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0009_alter_profile_profile_picture'),
        ('long_short_strategy', '0004_remove_longshortequity_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='longshortequity',
            old_name='position_side_per_sector',
            new_name='position_side',
        ),
        migrations.AlterUniqueTogether(
            name='longshortequity',
            unique_together={('user', 'strategies_list', 'market_cap', 'position_side', 'min_stock_price', 'sector', 'formula', 'sort_ascending')},
        ),
    ]
