# Generated by Django 5.1.2 on 2024-11-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0004_rename_financialreport_financialreportq22023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportJan2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_short_strategy.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='FinancialReportQ22023',
        ),
    ]
