# Generated by Django 5.1.2 on 2024-11-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0005_financialreportjan2023_delete_financialreportq22023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReportJan2023',
            new_name='FinancialReportJuly2023',
        ),
    ]
