# Generated by Django 5.1.2 on 2024-11-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0006_rename_financialreportjan2023_financialreportjuly2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReportJuly2023',
            new_name='FinancialReportJul2023',
        ),
    ]
