# Generated by Django 5.1.2 on 2024-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0007_rename_financialreportjuly2023_financialreportjul2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportjul2023',
            name='financial_data',
            field=models.JSONField(null=True),
        ),
    ]
