# Generated by Django 5.1.2 on 2024-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0008_financialreportjul2023_financial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreportjul2023',
            name='financial_data',
        ),
        migrations.RemoveField(
            model_name='financialreportjul2023',
            name='report_date',
        ),
        migrations.AddField(
            model_name='financialreportjul2023',
            name='Jul23',
            field=models.JSONField(null=True),
        ),
    ]
