# Generated by Django 5.1.2 on 2024-11-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0009_remove_financialreportjul2023_financial_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReportJul2023',
            new_name='FinancialReport',
        ),
    ]
