# Generated by Django 5.1.2 on 2024-11-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0010_rename_financialreportjul2023_financialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_short_strategy.stock', unique=True),
        ),
    ]
