# Generated by Django 5.1.2 on 2024-11-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0011_alter_financialreport_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='long_short_strategy.stock'),
        ),
    ]
