# Generated by Django 5.1.2 on 2024-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0012_alter_financialreport_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='Jul23',
        ),
    ]
