# Generated by Django 5.1.2 on 2024-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0013_remove_financialreport_jul23'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='Jul23',
            field=models.JSONField(null=True),
        ),
    ]
