# Generated by Django 5.1.2 on 2024-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0015_financialreport_apr23_financialreport_aug23_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='Apr24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Aug24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Dec24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Feb24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Jan24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Jul24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Jun24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Mar24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='May24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Nov24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Oct24',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='Sep24',
            field=models.JSONField(null=True),
        ),
    ]
