# Generated by Django 5.1.2 on 2024-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0017_alter_stock_ipo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.IntegerField(null=True),
        ),
    ]
