# Generated by Django 5.1.2 on 2024-11-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0022_remove_candlestick_long_short__stock_i_85bb62_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='ticker',
        ),
    ]
