# Generated by Django 5.1.2 on 2024-11-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0024_alter_balancesheet_date_alter_cashflow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
