# Generated by Django 5.1.2 on 2024-11-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0026_alter_balancesheet_date_alter_cashflow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='BasicEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='DilutedEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='TaxRateForCalcs',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='BasicEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='DilutedEPS',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='TaxEffectOfUnusualItems',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='TaxRateForCalcs',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
