# Generated by Django 5.1.2 on 2024-11-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_short_strategy', '0028_alter_balancesheet_stock_alter_cashflow_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeStatement',
        ),
    ]
